import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Link from "next/link";
import HeroSection from "@/src/HeroSection";
const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>SnapScape</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroSection />
      
      <main className="container mx-auto py-36 px-8">
        <div className="grid md:grid-cols-3 gap-6">
          {data.map((item) => (
            <div key={item.id} className=" bg-white border border-gray-200 rounded-lg shadow">
              <Link href={`/${item.id}`}>
                <Image
                  className="rounded-t-lg object-cover object-center w-full h-72"
                  src={item.image}
                  alt={item.title}
                  width={300}
                  height={300}
                />
                <h2 className="mb-2 text-center text-2xl font-bold tracking-tight text-gray-900">
                  {item.title}
                </h2>
              </Link>
            </div>
          ))}
        </div>
      </main>

    </>
  );
}

export async function getServerSideProps() {
  const { image_items } = await import("/data/data.json");
  return {
    props: {
      data: image_items,
    },
  };
}
